// Generated endpoints
const endpoints = [
    { endpoint: 'add_admin', methods: ['POST'], allowed_args: ['player_id', 'role', 'description'] },
    { endpoint: 'add_blacklist_record', methods: ['POST'], allowed_args: ['player_id', 'blacklist_id', 'reason', 'expires_at', 'admin_name'] },
    { endpoint: 'add_map_to_rotation', methods: ['POST'], allowed_args: ['map_name', 'after_map_name', 'after_map_name_number'] },
    { endpoint: 'add_map_to_votemap_whitelist', methods: ['POST'], allowed_args: ['map_name'] },
    { endpoint: 'add_maps_to_rotation', methods: ['POST'], allowed_args: ['map_names'] },
    { endpoint: 'add_maps_to_votemap_whitelist', methods: ['POST'], allowed_args: ['map_names'] },
    { endpoint: 'add_message_template', methods: ['POST'], allowed_args: ['title', 'content', 'category', 'by'] },
    { endpoint: 'add_vip', methods: ['POST'], allowed_args: ['player_id', 'description', 'expiration'] },
    { endpoint: 'ban_profanities', methods: ['POST'], allowed_args: ['profanities'] },
    { endpoint: 'clear_cache', methods: ['POST'], allowed_args: [] },
    { endpoint: 'create_blacklist', methods: ['POST'], allowed_args: ['name', 'sync', 'servers'] },
    { endpoint: 'delete_blacklist', methods: ['POST'], allowed_args: ['blacklist_id'] },
    { endpoint: 'delete_blacklist_record', methods: ['POST'], allowed_args: ['record_id'] },
    { endpoint: 'delete_message_template', methods: ['POST'], allowed_args: ['id'] },
    { endpoint: 'describe_admin_pings_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_audit_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_auto_broadcasts_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_auto_mod_level_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_auto_mod_no_leader_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_auto_mod_seeding_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_auto_mod_solo_tank_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_camera_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_camera_notification_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_chat_commands_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_chat_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_expired_vip_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_kills_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_log_line_webhook_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_log_stream_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_name_kick_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_rcon_chat_commands_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_rcon_connection_settings_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_rcon_server_settings_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_real_vip_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_scorebot_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_seed_vip_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_server_name_change_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_standard_broadcast_messages', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_standard_punishments_messages', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_standard_welcome_messages', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_steam_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_tk_ban_on_connect_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_vac_game_bans_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_votekick_autotoggle_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_votemap_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'describe_watchlist_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'do_service', methods: ['POST'], allowed_args: [] },
    { endpoint: 'download_vips', methods: ['GET'], allowed_args: [] },
    { endpoint: 'edit_blacklist', methods: ['POST'], allowed_args: ['blacklist_id', 'name', 'sync_method', 'servers'] },
    { endpoint: 'edit_blacklist_record', methods: ['POST'], allowed_args: ['record_id', 'blacklist_id', 'reason', 'expires_at'] },
    { endpoint: 'edit_message_template', methods: ['POST'], allowed_args: ['id', 'title', 'content', 'category', 'by'] },
    { endpoint: 'flag_player', methods: ['POST'], allowed_args: ['player_id', 'flag', 'player_name', 'comment'] },
    { endpoint: 'get_admin_groups', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_admin_ids', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_admin_pings_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_all_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_all_message_templates', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_all_standard_message_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_audit_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_audit_logs', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_audit_logs_autocomplete', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_auto_broadcasts_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_auto_mod_level_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_auto_mod_no_leader_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_auto_mod_seeding_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_auto_mod_solo_tank_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_auto_settings', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_autobalance_enabled', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_autobalance_threshold', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_ban', methods: ['GET'], allowed_args: ['player_id'] },
    { endpoint: 'get_bans', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_blacklist', methods: ['GET'], allowed_args: ['blacklist_id'] },
    { endpoint: 'get_blacklist_records', methods: ['GET'], allowed_args: ['player_id', 'reason', 'blacklist_id', 'exclude_expired', 'page_size', 'page'] },
    { endpoint: 'get_blacklists', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_broadcast_message', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_camera_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_camera_notification_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_chat_commands_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_chat_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_connection_info', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_current_map_sequence', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_date_scoreboard', methods: ['GET'], allowed_args: ['start', 'end'] },
    { endpoint: 'get_detailed_player_info', methods: ['GET'], allowed_args: ['player_name', 'player'] },
    { endpoint: 'get_detailed_players', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_expired_vip_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_gamestate', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_historical_logs', methods: ['GET', 'POST'], allowed_args: ['player_name', 'player_id', 'action', 'limit', 'from_', 'till', 'time_sort', 'exact_player_match', 'exact_action', 'server_filter'] },
    { endpoint: 'get_idle_autokick_time', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_ingame_mods', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_kills_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_live_game_stats', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_live_scoreboard', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_log_line_webhook_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_log_stream_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_logs', methods: ['GET'], allowed_args: ['since_min_ago', 'filter_', 'by'] },
    { endpoint: 'get_map', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_map_history', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_map_rotation', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_map_scoreboard', methods: ['GET'], allowed_args: ['map_id'] },
    { endpoint: 'get_map_shuffle_enabled', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_maps', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_max_ping_autokick', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_message_template', methods: ['GET'], allowed_args: ['id'] },
    { endpoint: 'get_message_template_categories', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_message_templates', methods: ['GET'], allowed_args: ['category'] },
    { endpoint: 'get_name', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_name_kick_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_next_map', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_objective_row', methods: ['GET'], allowed_args: ['row'] },
    { endpoint: 'get_objective_rows', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_online_mods', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_own_user_permissions', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_perma_bans', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_player_comments', methods: ['GET'], allowed_args: ['player_id'] },
    { endpoint: 'get_player_info', methods: ['GET'], allowed_args: ['player_name', 'can_fail'] },
    { endpoint: 'get_player_messages', methods: ['GET'], allowed_args: ['player_id'] },
    { endpoint: 'get_player_profile', methods: ['GET'], allowed_args: ['player_id', 'num_sessions'] },
    { endpoint: 'get_playerids', methods: ['GET'], allowed_args: ['as_dict'] },
    { endpoint: 'get_players', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_players_history', methods: ['GET', 'POST'], allowed_args: ['page', 'page_size', 'last_seen_from', 'last_seen_till', 'player_id', 'player_name', 'blacklisted', 'is_watched', 'exact_name_match', 'ignore_accent', 'flags', 'country'] },
    { endpoint: 'get_previous_map', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_profanities', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_public_info', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_queue_length', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_rcon_chat_commands_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_rcon_connection_settings_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_rcon_server_settings_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_real_vip_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_recent_logs', methods: ['GET', 'POST'], allowed_args: ['filter_player', 'filter_action', 'inclusive_filter', 'start', 'end', 'exact_player_match', 'exact_action'] },
    { endpoint: 'get_round_time_remaining', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_scoreboard_maps', methods: ['GET'], allowed_args: ['page'] },
    { endpoint: 'get_scorebot_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_seed_vip_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_server_list', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_server_name_change_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_server_settings', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_services', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_slots', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_standard_broadcast_messages', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_standard_punishments_messages', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_standard_welcome_messages', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_status', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_steam_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_structured_logs', methods: ['GET'], allowed_args: ['since_min_ago', 'filter_action', 'filter_player'] },
    { endpoint: 'get_team_objective_scores', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_team_switch_cooldown', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_team_view', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_temp_bans', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_tk_ban_on_connect_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_vac_game_bans_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_version', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_vip_ids', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_vip_slots_num', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_vips_count', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_votekick_autotoggle_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_votekick_enabled', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_votekick_thresholds', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_votemap_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_votemap_status', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_votemap_whitelist', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_watchlist_discord_webhooks_config', methods: ['GET'], allowed_args: [] },
    { endpoint: 'get_welcome_message', methods: ['GET'], allowed_args: [] },
    { endpoint: 'is_logged_in', methods: ['GET'], allowed_args: [] },
    { endpoint: 'kick', methods: ['POST'], allowed_args: ['player_name', 'reason', 'by', 'player_id'] },
    { endpoint: 'login', methods: ['POST'], allowed_args: [] },
    { endpoint: 'logout', methods: ['GET', 'POST'], allowed_args: [] },
    { endpoint: 'message_player', methods: ['POST'], allowed_args: ['player_name', 'player_id', 'message', 'by', 'save_message'] },
    { endpoint: 'perma_ban', methods: ['POST'], allowed_args: ['player_name', 'player_id', 'reason', 'by'] },
    { endpoint: 'post_player_comment', methods: ['POST'], allowed_args: ['player_id', 'comment', 'by'] },
    { endpoint: 'punish', methods: ['POST'], allowed_args: ['player_name', 'reason', 'by'] },
    { endpoint: 'reconnect_gameserver', methods: ['POST'], allowed_args: [] },
    { endpoint: 'remove_admin', methods: ['POST'], allowed_args: ['player_id'] },
    { endpoint: 'remove_all_vips', methods: ['POST'], allowed_args: [] },
    { endpoint: 'remove_map_from_rotation', methods: ['POST'], allowed_args: ['map_name', 'map_number'] },
    { endpoint: 'remove_map_from_votemap_whitelist', methods: ['POST'], allowed_args: ['map_name'] },
    { endpoint: 'remove_maps_from_rotation', methods: ['POST'], allowed_args: ['map_names'] },
    { endpoint: 'remove_maps_from_votemap_whitelist', methods: ['POST'], allowed_args: ['map_names'] },
    { endpoint: 'remove_perma_ban', methods: ['POST'], allowed_args: ['player_id'] },
    { endpoint: 'remove_temp_ban', methods: ['POST'], allowed_args: ['player_id'] },
    { endpoint: 'remove_vip', methods: ['POST'], allowed_args: ['player_id'] },
    { endpoint: 'reset_map_votemap_whitelist', methods: ['POST'], allowed_args: [] },
    { endpoint: 'reset_votekick_thresholds', methods: ['POST'], allowed_args: [] },
    { endpoint: 'reset_votemap_state', methods: ['POST'], allowed_args: [] },
    { endpoint: 'run_raw_command', methods: ['GET', 'POST'], allowed_args: [] },
    { endpoint: 'set_admin_pings_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_audit_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_auto_broadcasts_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_auto_mod_level_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_auto_mod_no_leader_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_auto_mod_seeding_config', methods: ['POST'], allowed_args: ['by', 'user_config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_auto_mod_solo_tank_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_auto_settings', methods: ['POST'], allowed_args: [] },
    { endpoint: 'set_autobalance_enabled', methods: ['POST'], allowed_args: ['value'] },
    { endpoint: 'set_autobalance_threshold', methods: ['POST'], allowed_args: ['max_diff'] },
    { endpoint: 'set_broadcast', methods: ['POST'], allowed_args: ['message'] },
    { endpoint: 'set_camera_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_camera_notification_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_chat_commands_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_chat_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_expired_vip_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_game_layout', methods: ['POST'], allowed_args: ['objectives', 'random_constraints'] },
    { endpoint: 'set_idle_autokick_time', methods: ['POST'], allowed_args: ['minutes'] },
    { endpoint: 'set_kills_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_log_line_webhook_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_log_stream_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_map', methods: ['POST'], allowed_args: ['map_name'] },
    { endpoint: 'set_map_shuffle_enabled', methods: ['POST'], allowed_args: ['enabled'] },
    { endpoint: 'set_maprotation', methods: ['POST'], allowed_args: ['map_names'] },
    { endpoint: 'set_max_ping_autokick', methods: ['POST'], allowed_args: ['max_ms'] },
    { endpoint: 'set_name_kick_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_profanities', methods: ['POST'], allowed_args: ['profanities'] },
    { endpoint: 'set_queue_length', methods: ['POST'], allowed_args: ['value'] },
    { endpoint: 'set_rcon_chat_commands_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_rcon_connection_settings_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_rcon_server_settings_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_real_vip_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_scorebot_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_seed_vip_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_server_name', methods: ['POST'], allowed_args: ['name'] },
    { endpoint: 'set_server_name_change_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_standard_broadcast_messages', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_standard_punishments_messages', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_standard_welcome_messages', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_steam_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_team_switch_cooldown', methods: ['POST'], allowed_args: ['minutes'] },
    { endpoint: 'set_tk_ban_on_connect_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_vac_game_bans_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_vip_slots_num', methods: ['POST'], allowed_args: ['value'] },
    { endpoint: 'set_votekick_autotoggle_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_votekick_enabled', methods: ['POST'], allowed_args: ['value'] },
    { endpoint: 'set_votekick_thresholds', methods: ['POST'], allowed_args: ['threshold_pairs'] },
    { endpoint: 'set_votemap_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_votemap_whitelist', methods: ['POST'], allowed_args: ['map_names'] },
    { endpoint: 'set_watchlist_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'set_welcome_message', methods: ['POST'], allowed_args: ['message'] },
    { endpoint: 'switch_player_now', methods: ['POST'], allowed_args: ['player_name'] },
    { endpoint: 'switch_player_on_death', methods: ['POST'], allowed_args: ['player_name', 'by'] },
    { endpoint: 'temp_ban', methods: ['POST'], allowed_args: ['player_name', 'player_id', 'duration_hours', 'reason', 'by'] },
    { endpoint: 'unban', methods: ['POST'], allowed_args: ['player_id'] },
    { endpoint: 'unban_profanities', methods: ['POST'], allowed_args: ['profanities'] },
    { endpoint: 'unblacklist_player', methods: ['POST'], allowed_args: ['player_id'] },
    { endpoint: 'unflag_player', methods: ['POST'], allowed_args: ['flag_id', 'player_id', 'flag'] },
    { endpoint: 'unwatch_player', methods: ['POST'], allowed_args: ['player_id'] },
    { endpoint: 'upload_vips', methods: ['POST'], allowed_args: [] },
    { endpoint: 'upload_vips_result', methods: ['GET'], allowed_args: [] },
    { endpoint: 'validate_admin_pings_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_audit_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_auto_broadcasts_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_auto_mod_level_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_auto_mod_no_leader_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_auto_mod_seeding_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_auto_mod_solo_tank_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_camera_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_camera_notification_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_chat_commands_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_chat_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_expired_vip_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_kills_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_log_line_webhook_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_log_stream_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_name_kick_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_rcon_chat_commands_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_rcon_connection_settings_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_rcon_server_settings_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_real_vip_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_scorebot_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_seed_vip_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_server_name_change_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_standard_broadcast_messages', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_standard_punishments_messages', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_standard_welcome_messages', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_steam_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_tk_ban_on_connect_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_vac_game_bans_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_votekick_autotoggle_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_votemap_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'validate_watchlist_discord_webhooks_config', methods: ['POST'], allowed_args: ['by', 'config', 'reset_to_default', 'kwargs'] },
    { endpoint: 'watch_player', methods: ['POST'], allowed_args: ['player_id', 'reason', 'by', 'player_name'] },
];

module.exports = endpoints;